---
title: "CV"

output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/git/cv/svm-latex-cv.tex
geometry: margin=1in

author: K. Bret Staudt Willet

jobtitle: "Ph.D. Candidate, Michigan State University"
# address: ""
fontawesome: yes

email: staudtwi@msu.edu
twitter: bretsw
github: bretsw
linkedin: bretsw
scholar: bretsw
web: bretsw.com
# phone: ""
updated: yes

keywords: networked learning, online communities, social media

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 9pt
linkcolor: blue
urlcolor: blue

# credit to Steven Miller
# http://svmiller.com/blog/2016/03/svm-r-markdown-cv/
# https://github.com/svmiller/svm-r-markdown-templates

# Rmarkdown guide: https://rmarkdown.rstudio.com/authoring_basics.html

---

# Education

## Michigan State University

**Ph.D.**, Educational Psychology & Educational Technology \hfill Expected 2020

  * \* Dissertation: *Into the edu-verse: New teachers seeking induction support on social media*
  * \* Committee: Matthew Koehler, Christine Greenhow, Ralph Putnam, Gail Richmond
  * \* Defended proposal: November 26, 2019

**M.A.**, Educational Technology \hfill 2015  
**Graduate Certificate**, Serious Game Design and Research \hfill 2014

## Bucknell University

**B.A.**, Mathematics & Sociology \hfill 2003

---

# Awards

**Clifford E. Erickson Memorial Fund Scholarship** \hfill 2020  
Michigan State University, College of Education \hfill East Lansing MI

**Featured Research** \hfill 2020  
Association for Educational Communications and Technology (AECT) International Convention \hfill Online

**Outstanding Paper Award** \hfill 2020  
Society for Information Technology & Teacher Education (SITE) International Conference \hfill Online

**Disciplinary Leadership Award** \hfill 2019  
Michigan State University, Council of Graduate Students \hfill East Lansing MI

**Outstanding Paper Award** \hfill 2019  
Society for Information Technology & Teacher Education (SITE) International Conference \hfill Las Vegas NV

**Outstanding Paper Award** \hfill 2017  
Society for Information Technology & Teacher Education (SITE) International Conference \hfill Austin TX

---

# Research

## Peer-Reviewed Journal Articles (11)

**Staudt Willet**, K. B., & Carpenter, J. P. (in press). A tale of two subreddits: Change and continuity in teaching-related online spaces. *British Journal of Educational Technology*.

Greenhalgh, S. P., Rosenberg, J. M., **Staudt Willet**, K. B., Koehler, M. J., & Akcaoglu, M. (2020). Identifying multiple learning spaces within a single teacher-focused Twitter hashtag. *Computers and Education*. https://doi.org/10.1016/j.compedu.2020.103809

**Staudt Willet**, K. B., & Carpenter, J. P. (2020). Teachers on Reddit? Exploring contributions and interactions in four teaching-related subreddits. *Journal of Research on Technology in Education, 52*, 216-233. https://doi.org/10.1080/15391523.2020.1722978

Carpenter, J. P., **Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2020). Spam and educators’ Twitter use: Methodological considerations and challenges. *TechTrends, 64*, 460-469. https://doi.org/10.1007/s11528-019-00466-3

Greenhalgh, S. P., **Staudt Willet**, K. B., & Koehler, M. J. (2019). Approaches to Mormon identity and practice in the #ldsconf Twitter hashtag. *Journal of Media and Religion, 18*(4), 122-133. https://doi.org/10.1080/15348423.2019.1696121

Greenhow, C. M., Galvin, S., & **Staudt Willet**, K. B. (2019). What should be the role of social media in education? *Policy Insights from the Behavioral and Brain Sciences, 6*(2), 178-185. https://doi.org/10.1177/2372732219865290

Greenhow, C. M., Gleason, B., & **Staudt Willet**, K. B. (2019). Social scholarship revisited: Changing scholarly practices in the age of social media. *British Journal of Educational Technology, 50*, 987-1004. https://doi.org/10.1111/bjet.12772

Krutka, D. G., Heath, M. K., & **Staudt Willet**, K. B. (2019). Foregrounding technoethics: Toward critical perspectives in technology and teacher education. *Journal of Technology and Teacher Education, 27*(4), 555-574. http://learntechlib.org/p/208235/

**Staudt Willet**, K. B. (2019). Revisiting how and why educators use Twitter: Tweet types and purposes in #Edchat. *Journal of Research on Technology in Education, 51*, 273-289. https://doi.org/10.1080/15391523.2019.1611507

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., & Koehler, M. J. (2018). Tweet, and we shall find: Using digital methods to locate participants in educational hashtags. *TechTrends, 62*, 501-508. https://doi.org/10.1007/s11528-018-0313-6

Greenhow, C. M., Gleason, B., Marich, H., & **Staudt Willet**, K. B. (2017). Educating social scholars: Examining novice researchers’ practices with social media. *Qwerty – Open and Interdisciplinary Journal of Technology, Culture and Education, 12*(2), 30-45. http://www.ckbg.org/qwerty/index.php/qwerty/article/view/269/

## Book Chapters (6)

**Staudt Willet**, K. B. (in press). The hashtag-thread mashup: Differences in Twitter #Edchat replies. In D. C. Gibson & M. N. Ochoa (Eds.), *Research highlights in technology and teacher education 2020*. Association for the Advancement of Computing in Education (AACE). [Invited revision of conference presentation in an edited book]

Greenhalgh, S. P., Koehler, M. J., Rosenberg, J. M., & **Staudt Willet**, K. B. (2021). Considerations for using social media data in learning design and technology research. In E. Romero-Hall (Ed.), *Research methods in learning design & technology*. Routledge.

Greenhow, C. M., Galvin, S., & **Staudt Willet**, K. B. (2020). Research methods unique to digital contexts: An introduction to virtual ethnography. In N. K. Duke & M. H. Mallette (Eds.), *Literacy research methodologies* (3rd ed.). Guilford. 

**Staudt Willet**, K. B., & Carpenter, J. P. (2019). Educators on the front page of the Internet: Teacher learning in four subreddits. In D. C. Gibson & M. N. Ochoa (Eds.), *Research highlights in technology and teacher education 2019* (pp. 169-178). Association for the Advancement of Computing in Education (AACE). https://www.learntechlib.org/p/210591/ [Invited revision of conference presentation in an edited book]

**Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2018). A tweet by any other frame: Three approaches to studying educator interactions on Twitter. In T. J. Bastiaens & G. Marks (Eds.), *Education and Information Technology Annual 2018: A Selection of AACE Award Papers* (pp. 67-74). Association for the Advancement of Computing in Education (AACE).  http://learntechlib.org/p/182952/ [Invited reprint of conference presentation in an edited book]

**Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2017). A tweet by any other frame: Comparing three theoretical frameworks for studying educator interactions on Twitter. In L. Liu & D. Gibson (Eds.), *Research highlights in technology and teacher education 2017* (pp. 63-70). Association for the Advancement of Computing in Education (AACE).  http://www.learntechlib.org/p/180960/ [Invited revision of conference presentation in an edited book]

## Peer-Reviewed Conference Proceedings (14)

Krutka, D. G., Heath, M. K., & **Staudt Willet**, K. B. (2020, April). *Foregrounding critical technoethics in technology and teacher education: A workshop for pedagogical action* Paper presented at the Society for Information Technology & Teacher Education (SITE) International Conference 2020, New Orleans, LA.

**Staudt Willet**, K. B. (2020, April). Early-career educators’ experiences with social media during induction. In G. H. Marks & D. Schmidt-Crawford (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2020* (pp. 1256-1262). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/215917/ 

**Staudt Willet**, K. B. (2020, April). The hashtag-thread mashup: How educators talk to each other in Twitter #Edchat. In G. H. Marks & D. Schmidt-Crawford (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2020* (pp. 1270-1280). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/215919/

**Staudt Willet**, K. B., & Carpenter, J. P. (2020, April). For the longest time: Continuity and change in one teaching-related subreddit. In G. H. Marks & D. Schmidt-Crawford (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2020* (pp. 1263-1269). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/215918/

Carpenter, J. P., Koehler, M. J., **Staudt Willet**, K. B., & Greenhalgh, S. P. (2019, March). Spam, spam, spam, spam: Methodological considerations and challenges for studying educators’ Twitter use. In K. Graziano (Ed.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2019* (pp. 2702-2711). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/208033/

Moudgalya, S. K., & **Staudt Willet**, K. B. (2019, March). Communities and clusters: User interactions in an online discussion forum for computer science education. In K. Graziano (Ed.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2019* (pp. 2291-2298). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/207968/

**Staudt Willet**, K. B. (2019, March). #Edchat is bigger, but better only for some: Revisiting how and why educators use Twitter. In K. Graziano (Ed.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2019* (pp. 2778-2786). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/208039/

**Staudt Willet**, K. B., & Carpenter, J. P. (2019, March). Educators on the front page of the Internet: Education-related subreddits as learning spaces. In K. Graziano (Ed.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2019* (pp. 2787-2795). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/208040/

**Staudt Willet**, K. B., & Willet, B. D. (2018, October). Look who’s talking: Using human coding to establish a machine learning approach to Twitter education chats. In *AoIR selected papers of internet research*. Association of Internet Researchers.  https://spir.aoir.org/ojs/index.php/spir/article/view/10512

**Staudt Willet**, K. B., & Reimer, P. N. (2018, March). The career you save may be your own: Exploring the mathtwitterblogosphere as a community of practice. In E. Langran & J. Borup (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2018* (pp. 2324-2329). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/182845/

**Staudt Willet**, K. B., Moudgalya, S., Boltz, L. O., Greenhalgh, S. P., & Koehler, M. J. (2018, March). Back to the gaming board: Understanding games and education through board game reviews. In E. Langran & J. Borup (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2018* (pp. 495-503). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/182570/

Greenhow, C., Marich, H., & **Staudt Willet**, K .B. (2017, March). Social scholars: Re-envisioning graduate education in the age of social media. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 856-861). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/177363/

Rosenberg, J., Akcaoglu, M., **Staudt Willet**, K. B., Greenhalgh, S., & Koehler, M. (2017, March). A tale of two Twitters: Synchronous and asynchronous use of the same hashtag. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 283-286). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/177856/

**Staudt Willet**, K. B., Koehler, M. J., & Greenhalgh, S. P. (2017, March). A tweet by any other frame: Three approaches to studying educator interactions on Twitter. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 1823-1830). Association for the Advancement of Computing in Education (AACE).  https://www.learntechlib.org/p/177469/

## Peer-Reviewed Conference Presentations (23)

**Staudt Willet**, K. B. (2020, November). *Into the edu-verse: New teachers’ challenges, supports, and social media*. Association for Educational Communications and Technology (AECT) International Convention 2020, Online.

**Staudt Willet**, K. B., & Carpenter, J. P. (2020, November). *Time after time: Continuity and change in teaching-related subreddits* [Featured research]. Association for Educational Communications and Technology (AECT) International Convention 2020, Online.

Rutherford, T., Rosenberg, J. M., & **Staudt Willet**, K. B. (2020, April). Which birds fill the branches of the AERA Twitter tree? Twitter networks around #AERA19. In P. N. Beymer, D. K. Benden, & M. L. Bernacki (Chairs), *Affordances and modeling of intensive data* [Structured Poster Session]. American Educational Research Association (AERA) Annual Meeting 2020, San Francisco, CA. (Conference canceled)

**Staudt Willet**, K. B. (2020, April). *Can you hear me now? Teachers’ versus researchers’ measures of the Twitter #Edchat affinity space* [Paper session]. American Educational Research Association (AERA) Annual Meeting 2020, San Francisco, CA. (Conference canceled)

**Staudt Willet**, K. B., Heath, M. K., & Krutka, D. G. (2020, April). *The need for technoethics in teacher education: A critical analysis of literature* [Poster session]. American Educational Research Association (AERA) Annual Meeting 2020, San Francisco, CA. (Conference canceled)

Greenhalgh, S. P., **Staudt Willet**, K. B., & Koehler, M. J.(2019, October). *Twitter hashtags and religious learning: Mormon identity and participatory practice in #ldsconf.* Association for Educational Communications and Technology (AECT) International Convention 2019, Las Vegas, NV.

**Staudt Willet**, K. B., & Bagdy, L. (2019, October). *How do you do, fellow kids? "New teachers" in Twitter #ntchat.* Association for Educational Communications and Technology (AECT) International Convention 2019, Las Vegas, NV.

**Staudt Willet**, K. B., & Moudgalya, S. K. (2019, October). *Community, network, or space: Conceptualizing inspired professional learning in an online discussion forum.* Association for Educational Communications and Technology (AECT) International Convention 2019, Las Vegas, NV.

Greenhow, C. M., **Staudt Willet**, K. B., & Marich, H. (2019, July). *Scholarship reconsidered: Examining new scholars’ social media practices.* The 10th International Conference on Social Media & Society 2019, Toronto, ON, Canada.

**Staudt Willet**, K. B. (2019, April). *Is bigger better? Exploring educators’ uses and gratifications in Twitter #Edchat.* American Educational Research Association (AERA) Annual Meeting 2019, Toronto, ON, Canada. 

Greenhalgh, S. P., Koehler, M. J., & **Staudt Willet**, K. B. (2019, March). *Every nation, kindred, tongue, and “tweeple”: International use of the #ldsconf Twitter hashtag.* Decentered Mormonism Conference 2019, Bordeaux, France.

**Staudt Willet**, K. B. (2018, October). *Cyborg methods: The benefits of mixing human and machine coding.* Association for Educational Communications and Technology (AECT) International Convention 2018, Kansas City, MO.

**Staudt Willet**, K. B. (2018, October). *Self-promoters, bots, and moderators: Exploring educators’ participatory actions, roles, and culture in Twitter #Edchat.* Association for Educational Communications and Technology (AECT) International Convention 2018, Kansas City, MO.

**Staudt Willet**, K. B. (2018, October). *Teacher participation in digital spaces: What kinds of learning spaces are on Reddit?* Association for Educational Communications and Technology (AECT) International Convention 2018, Kansas City, MO.

**Staudt Willet**, K. B., Greenhalgh, S. P., Rosenberg, J. M., Koehler, M. J. (2018, October). *Won’t you be my neighbor? How education stakeholders use hyperlinks to build information neighborhoods on Twitter.* Association for Educational Communications and Technology (AECT) International Convention 2018, Kansas City, MO.

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., Akcaoglu, M., & Koehler, M. J. (2018, April). *Timing is everything: Comparing synchronous and asynchronous modes of Twitter for teacher professional learning.* American Educational Research Association (AERA) Annual Meeting 2018, New York, NY. 

Greenhow, C. M., Brandon, D. L., Greenhalgh, S. P., Koehler, M. J., **Staudt Willet**, K. B., & Li, J. (2018, April). *Tweeting toward the PhD: Exploring new scholars’ practices with social media.* American Educational Research Association (AERA) Annual Meeting 2018, New York, NY.

Greenhalgh, S. P., **Staudt Willet**, K. B., Rosenberg, J. M., & Koehler, M. J. (2017, November). *No accounting for theory? The case for an affinity space approach to educational hashtag research.* Association for Educational Communications and Technology (AECT) International Convention 2017, Jacksonville, FL.

**Staudt Willet**, K. B. (2017, August). *When a little blue bird flaps its wings: How Twitter is changing the world.* Passion Talks Conference 2017, Google Headquarters, Mountain View, CA.

**Staudt Willet**, K. B. (2016, August). *The strength of the weak ties.* Passion Talks Conference 2016, Google Headquarters, Mountain View, CA.

**Staudt Willet**, K. B. (2014, October). *My journey into user-centered game design.* North American Simulation and Game Association (NASAGA) International Conference 2014, Baltimore, MD.

**Staudt Willet**, K. B. (2013, October). *Tension: My favorite game mechanic.* North American Simulation and Game Association (NASAGA) International Conference 2013, Sarasota, FL.

**Willet**, K. B. (2001, February). *The shortest closed path on an arithmetic surface.* Moravian College Student Mathematics Conference 2001, Bethlehem, PA.

---

# Funding 

## TOTAL: $26,675

**Clifford E. Erickson Memorial Fund Scholarship: $5,500** \hfill 2020  
Michigan State University, College of Education \hfill East Lansing MI

**Student Research Conference Travel Fellowship: $600** \hfill 2020  
Michigan State University, Dept. of Counseling, Educational Psychology, & Special Ed. \hfill East Lansing MI

**Research Practicum/Dissertation Development Fellowship: $1,300** \hfill 2020  
Michigan State University, College of Education \hfill East Lansing MI

**Disciplinary Leadership Award: $2,000** \hfill 2019  
Michigan State University, Council of Graduate Students \hfill East Lansing MI

**Research Practicum/Dissertation Development Fellowship: $2,000** \hfill 2019  
Michigan State University, College of Education \hfill East Lansing MI

**Student Research Conference Travel Fellowship: $1,050** \hfill 2019  
Michigan State University, Dept. of Counseling, Educational Psychology, & Special Ed. \hfill East Lansing MI

**Summer Research Renewable Fellowship: $12,000** \hfill 2018-2019  
Michigan State University, College of Education \hfill East Lansing MI

**Professional Development Award: $500** \hfill 2018  
Michigan State University, Council of Graduate Students \hfill East Lansing MI

**Student Research Conference Travel Fellowship: $795** \hfill 2018  
Michigan State University, Dept. of Counseling, Educational Psychology, & Special Ed. \hfill East Lansing MI

**Student Research Conference Travel Fellowship: $930** \hfill 2017  
Michigan State University, Dept. of Counseling, Educational Psychology, & Special Ed., \hfill East Lansing MI

---

# Teaching

## Courses Taught (4)

**Teaching & Learning with Technology** (Undergraduate, online, 6x) \hfill 2017-present

* \* Course topics include design thinking, universal design for learning, media & information literacy, professional learning networks, computational thinking, and play-based learning. 
* \* Students develop plans for integrating technology in classroom.
* \* The semester-long project is to design a professional *online portfolio*.

**Learning Technology by Design** (Master’s, online, 3x) \hfill 2018-present

* \* Course topics include design thinking, the design process (empathize, define, ideate, prototype, test), designing for learners, iterative design. and collaboration in design.
* \* Students discuss examples of good and bad designs from everyday life.
* \* The semester-long project is to work through one cycle of the design process to address a *problem of practice* from the student's professional context.

**Electronic Assessment for Teaching and Learning** (Master’s, online, 2x) \hfill 2018-present

* \* Course topics include foundational theories of assessment, formative assessment, feedback, and a critical examination of methods for assessment (e.g., portfolios, rubrics, surveys, tests, self-evaluations).
* \* Students develop an *assessment design checklist* to use in their own professional practice.
* \* The semester-long project is to plan a *formative assessment design* to implement in their own context.

**Teaching Students Online** (Master’s, online, 1x) \hfill 2017

* \* Course topics include foundations for online learning, course management systems, various models of online course design, instructor-student communication, assessment, universal design for learning, and online classroom management.
* \* Students playfully explore Google Apps, course management systems, screencasting tools, and file management systems.
* \* The semester-long project is to design a curriculum for an *online course module* consisting of 3-5 interconnected lessons, which may include training sessions or non-traditional courses.

## Instructional Activities & Workshops (15)

**Staudt Willet**, K. B. (2020, October). *You are stronger than you think: Insights for academic publishing* [Guest lecture for doctoral course]. CEP 956: Mind, Media and Learning, Michigan State University: East Lansing, MI. https://bretsw.github.io/publishing-lecture

**Staudt Willet**, K. B. (2020, October). *Welcome to the good place?: Teachers' networked learning on social media* [Guest lecture for Master's course]. Teaching with Technology, Manhattanville College, Purchase, NY. https://bretsw.github.io/manhattanville-lecture

Budhrani, K., Ross, K., Muljana, P., Dyer, R., Jones, M., & **Staudt Willet**, K. B. (2020, November). *Factors influencing doctoral students’ perseverance in online instructional technology programs* [Panel]. Association for Educational Communications and Technology (AECT) International Convention 2020, Online.

Romero-Hall, E., Arslan-Ari, I., Gentry, W., Greenhalgh, S., Jung, Y. J., Stefaniak, J., Tiwari, S., Koehler, M., Rosenberg, J., **Staudt Willet**, K. B., Lockee, B., Zimmerman, H., Pérez-Edgar, K., Grant, M. M., & Ari, F. (2020, November). *Let’s talk about research methods: Where are we today?* [Panel]. Association for Educational Communications and Technology (AECT) International Convention 2020, Online.

**Staudt Willet**, K. B., Greenhalgh, S. P., & Rosenberg, J. M. (2020, November). *Simple collection and powerful analysis of Twitter data using R* [Conference workshop]. Association for Educational Communications and Technology (AECT) International Convention 2020, Online.

**Staudt Willet**, K. B., Rosenberg, J. M., & Greenhalgh, S. P. (2020, March). *R u ready 4 R? Introduction to analyzing educational Internet data using R* [Workshop facilitated for the Students, Social Media & Schools research group at Florida State University]. Available from https://bretsw.github.io/fsu-workshop/

**Staudt Willet**, K. B., & Bork, W. (2019, December). *Electronic assessment* [Presentation for Master of Arts in Educational Technology (MAET) instructor huddle]. Michigan State University, East Lansing, MI.

**Staudt Willet**, K. B. (2019, November). *Content, conversation, & context: How educators talk to each other in Twitter #Edchat* [Presentation for Educational Psychology & Educational Technology PhD program brownbag seminar]. Michigan State University, East Lansing, MI.

**Staudt Willet**, K. B., Greenhalgh, S. P., & Rosenberg, J. M. (2019, October). *Online data and open source tools: Analyzing educational Internet data using R* [Conference workshop]. Association for Educational Communications and Technology (AECT) International Convention 2019, Las Vegas, NV. Available from https://bretsw.github.io/aect19-workshop/

**Staudt Willet**, K. B. (2019, September). *Insights for academic publishing* [Guest lecture for doctoral course]. CEP 956: Mind, Media and Learning, Michigan State University: East Lansing, MI.

**Staudt Willet**, K. B. (2018, November). *Bigger is not always better: Revisiting how and why educators use Twitter #Edchat* [Presentation for Educational Psychology & Educational Technology PhD program brownbag seminar]. Michigan State University, East Lansing, MI.

**Staudt Willet**, K. B. (2018, October). *Experiences from the practicum* [Panel for doctoral course]. CEP 955: Research Design and Methods for Educational Psychology and Educational Technology, Michigan State University, East Lansing, MI.

**Staudt Willet**, K. B. (2017, November). *Once more unto the practicum, dear friends: Research lessons from studying social interactions on social media* [Presentation for Educational Psychology & Educational Technology PhD program brownbag seminar]. Michigan State University, East Lansing, MI.

**Staudt Willet**, K. B. (2015, September). *Patterns of online communities* [Webinar]. Indigitous Sessions, Online.

**Staudt Willet**, K. B. (2014, March). *What games say* [Guest lecture for an undergraduate course in Film, Media, & Teacher Education]. Millersville University, Millersville, PA.

## Mentoring and Advising

\* Graduate mentor, *Undergraduate course instruction* (Madison Allen, MSU) \hfill 2020  
\* Graduate mentor, *Master's course instruction* (William Bork, MSU) \hfill 2019-2020  
\* Peer reviewer, *National Science Foundation (NSF) grant proposal* (Dr. Joshua Rosenberg, University of Tennessee, Knoxville) \hfill 2019  
\* Doctoral student member, *Research apprenticeship practicum committee* (Sarah Galvin, MSU) \hfill 2018-2019  
\* Graduate mentor, *Undergraduate course instruction* (Matthew Drazin, MSU) \hfill 2018-2019  
\* Data analyst, *Social network analysis for doctoral project* (Katie Schenkel, MSU) \hfill 2018  
\* Data analyst, *Content analysis for doctoral dissertation* (Colin Terry, MSU) \hfill 2018  
\* Graduate mentor, *Undergraduate course instruction* (Sukanya Moudgalya, MSU) \hfill 2017-2018

---

# Service

## Journal Article Reviews (5)

\* *American Journal of Education* (2) \hfill 2019-2020  
\* *Internet and Higher Education* (2) \hfill 2019  
\* *Learning, Media and Technology*, with Dr. Christine Greenhow, faculty reviewer \hfill 2016

## Service in Professional Organizations

**American Educational Research Association (AERA)** 

* \* *Conference Proposal Reviewer* \hfill 2020

**Association for Educational Communications & Technology (AECT)**

* \* *Communications Officer*, Research & Theory Division \hfill 2020-2021
* \* *Secretary*, Research & Theory Division \hfill 2019-2020
* \* *Conference Proposal Reviewer* \hfill 2019-2020
* \* *Graduate Student Representative*, Research & Theory Division \hfill 2018-2019
* \* *Webinar Team Leader*, Graduate Student Association \hfill 2018-2019

**Society for Information Technology and Teacher Education (SITE)**

* \* *Co-Chair*, Social Media SIG \hfill 2019-2021
* \* *Planning Committee Member*, SITE Interactive Conference \hfill 2020
* \* *Conference Proposal Reviewer* \hfill 2020
* \* *Graduate Student Intern*, Social Media SIG \hfill 2018-2019

**Passion Talks Conference (Google HQ, Mountain View CA)**

* \* *Science, Technology, & Innovation Track Chair* \hfill 2017
* \* *Conference Executive Committee Member* \hfill 2017

**Urbana International Conference (St. Louis MO)**

* \* *Hackathon Core Leadership Team Member* \hfill 2015
* \* *Hackathon Mentor Coordinator* \hfill 2015

**North American Simulation and Game Association (NASAGA)**

* \* *Board Member* \hfill 2013-2015
* \* *Conference Committee Member*, Annual Conference (Baltimore MD, Seattle WA) \hfill 2014-2015

---

# Professional Experience

**Graduate Assistant/Instructor** \hfill 2017-present  
Michigan State University, College of Education \hfill East Lansing MI  
Department of Counseling, Educational Psychology, & Special Education

* \* Taught courses at Master's and Undergraduate levels

**Executive Coach** \hfill 2020-present  
Black in Gaming \hfill United States  
http://www.blackingaming.com/

* \* Trained and mentored members of the core leadership team
* \* Designed and implemented strategy for organizational culture and collaboration through remote and asynchronous work

**Course Writer** \hfill 2019  
Concordia University, College of Education \hfill Portland OR  
Educational Technology and Learning Design program

* \* Wrote and designed all materials for a new Master's-level course: The Evolving Landscape of Educational Technology

**Founding National Director, Ministry in Digital Spaces** \hfill 2014-2017  
InterVarsity Christian Fellowship/USA \hfill United States

* \* Managed 51 projects related to online community building through video games and social media
* \* Supervised 8 project leads
* \* Hosted and directed 5 think tank gatherings (Atlanta, Austin, San Francisco)

**Area Director**, South Central Pennsylvania \hfill 2009-2014  
InterVarsity Christian Fellowship/USA

* \* Supervised 17 different staff
* \* Directed 11 conferences for undergraduate students from 7 colleges
* \* Delivered more than 100 talks at 13 different colleges and 8 inter-collegiate conferences
* \* Designed and facilitated 30 training seminars for staff and students

**Director**, Summer Justice Program in Lancaster PA \hfill 2006; 2009-2012  
InterVarsity Christian Fellowship/USA

* \* Designed and facilitated five 6-week immersive learning programs for undergraduate students
* \* Received training in Mexico City, Mexico

**Director**, Summer Justice Program in Manila, Philippines \hfill 2005  
InterVarsity Christian Fellowship/USA

* \* Designed and facilitated a 6-week immersive, experiential learning program for undergraduate students
* \* Received training in Addis Ababa, Ethiopia

**Campus Staff Minster**, Franklin & Marshall College \hfill 2003-2007  
InterVarsity Christian Fellowship/USA \hfill Lancaster PA

* \* Trained, coached, and supported more than 50 different undergraduate student volunteer leaders

**Presidential Fellow: Research Assistant**, Department of Sociology \hfill 2002-2003  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA

* \* Reviewed literature in social psychology and situational identity

**Presidential Fellow: Research Assistant**, Department of Mathematics \hfill 2000-2002  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA

* \* Assisted with research in L-functions and Maass form deformations

**Research Intern: Summer Research Experience for Undergraduates** (REU), Dept. of Mathematics \hfill 2000  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA

* \* Assisted with research in L-functions and Maass form deformations

**Calculus Tutor**, Department of Mathematics \hfill 1999-2000  
Bucknell University, College of Arts & Sciences \hfill Lewisburg PA

---

# Further Training

**Early Career Symposium** \hfill 2020  
Association for Educational Communications & Technology (AECT) \hfill Virtual Conference

**Reproducible Research** \hfill 2020  
Course Certificate – Johns Hopkins University \hfill Coursera.org

**Exploratory Data Analysis** \hfill 2019  
Course Certificate – Johns Hopkins University \hfill Coursera.org

**Doctoral Colloquium** \hfill 2018  
Association of Internet Researchers (AoIR) \hfill Montreal QC

**Methods for Analyzing and Modeling Textual Data** \hfill 2018  
Summer School Series on Methods for Computational Social Science \hfill Los Angeles CA

**Getting and Cleaning Data** \hfill 2018  
Course Certificate – Johns Hopkins University \hfill Coursera.org

**The Data Scientist’s Toolbox** \hfill 2018  
Course Certificate – Johns Hopkins University \hfill Coursera.org

**R Programming** \hfill 2017  
Course Certificate – Johns Hopkins University \hfill Coursera.org

**Game Design and Facilitation** \hfill 2012  
Workshop Certificate – The Thiagi Group at NASAGA \hfill Columbus OH

---

# Professional Affiliations

**Association for Educational Communications & Technology (AECT)**

* \* *Research & Theory Division*

**American Educational Research Association (AERA)**

* \* *Division C* – Learning & Instruction
* \* *Technology as an Agent of Change in Teaching & Learning* (TACTL) SIG

**Society for Information Technology & Teacher Education (SITE)**

* \* *Social Media SIG*

---
